### ISSUE TITLE
What are the advantages of using QSPI Flash FW for OpenMV?

### ISSUE THREAD

**Issue by Kabron287** [WeActStudio/MiniSTM32H7xx#10]
I tryed both variants( **Internal Flash** and **QSPI Flash** ) and see no differences.

**Comment by Kabron287** [comment]
Am I right that Flash Disk Size is larger?

**Comment by WeActTC** [comment]
Flash Disk Size is the same, the difference is internal: the program runs in internal Flash, QSPI Flash: the program runs in external Flash

**Comment by Kabron287** [comment]
I compared Flash Disks sizez in Weact board with QSPI OpenMV and original OpenMV H7 board. They are:
8 172 kB and 111 kB.
Does it means that in case of Weact board Flash Disk is created in SPI Flash?

**Comment by WeActTC** [comment]
YES

**Comment by Kabron287** [comment]
Thanks. I guess it has to be reflected in docs.

**Comment by WeActTC** [comment]
Emmm, it doesn't matter

**Comment by Kabron287** [comment]
To whom how
