### ISSUE TITLE
刷了最新 的openmv3.9没有nn模块

### ISSUE THREAD

**Issue by maysrp** [WeActStudio/MiniSTM32H7xx#12]
板子刷了最新 的openmv3.9 发现没有nn模块

**Comment by Jason-xy** [comment]
确实 刷了最新的3.9.4也没有

**Comment by Jason-xy** [comment]
> 板子刷了最新 的openmv3.9 发现没有nn模块

刚刚查了openmv的原版文档，神经网络模块是tf。
