### ISSUE TITLE
installer_x64 STM32Bootloader

### ISSUE THREAD

**Issue by Givy** [WeActStudio/MiniSTM32H7xx#22]
Hi,
Cant get the driver installed on Windows 10.  Can't find the WeAct connection to Windows 10 device Manager;; WeAct_HID_Flash_NETFramework4+ V10 FluentWPF 191220 X64:

> Soft Version: 1.0.0.0
> Windows Version: 6.2.9200.0
> MCU Enter The Bootloader Method
> Hold down the KEY to Repower or Reboot
> Language: en-US
> Searching for HID Device [0483:572A] ...
> ********************
> Error - HID Device [0483:572A] is not found
> Finish

Which "Key" ? , I have three buttons on this board!
Many Thanks.

**Comment by WeActStudio** [comment]
It meens K1 button
