### ISSUE TITLE
LCD orientation

### ISSUE THREAD

**Issue by jongwoon-choi** [WeActStudio/MiniSTM32H7xx#23]
I want to use LCD as Landscape mode.

I found the "03-LCD_Test" project is set up as Portrait mode, it is not easy for me to change to Landscape mode.
Would you tell me how to change from Portrait to Landscape mode in "03-LCD_Test" project?

Best regards,
Jongwoon

**Comment by WeActStudio** [comment]
You can read ST7735.c, and read an array of OrientationTab

**Comment by jongwoon-choi** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thanks for your answer.
--------- 원본 메일 ---------

    
        보낸사람: WeAct Studio ***@***.***>
        받는사람: WeActStudio/MiniSTM32H7xx ***@***.***>
        
            참조: Jongwoon Choi ***@***.***>, Author ***@***.***>
        
        날짜: 22.07.24 23:22 GMT +0900
        제목: Re: [WeActStudio/MiniSTM32H7xx] LCD orientation (Issue #23)
        
        
    
    
        
Closed #23 as completed.
