### ISSUE TITLE
Do your STM32H750 chips have working HASH and CRYP units?

### ISSUE THREAD

**Issue by Crest** [WeActStudio/MiniSTM32H7xx#27]
As confirmed by an STMicroelectronics employee in this [thread](https://community.st.com/s/question/0D53W000010RpinSAC/how-to-enable-the-stm32h750vbt6-hw-crypto) some STM32H750 chips have been shipped with fused off HASH and CRYP units resulting in 100% failure rate to write to any of their control and status registers. The date codes listed in [README.md](https://github.com/WeActTC/MiniSTM32H7xx/blob/master/README.md) for STM32H750 boards fall in the range of potentially defective chips.

Do your boards as offered on [AliExpress](https://www.aliexpress.com/item/1005001475058305.html) ship chips containing usable  HASH and CRYP units?

**Comment by WeActStudio** [comment]
At present, the boards we produce are all the chips of batch 21 and later.
