### ISSUE TITLE
How to use "02-EXTMEM_BOOT" example?

### ISSUE THREAD

**Issue by ZergOfSwarm** [WeActStudio/MiniSTM32H7xx#29]
I am a beginner, and to me need memory-mapped mode, where the external memory is
seen as an internal memory... And I downloaded and flashed your  example "02-EXTMEM_BOOT" but, nothing has changed.

PS - I have a board of your production "WeActTC STM32H750VBT6" and I am sure many of your customers In the same situation as I.

**Comment by WeActStudio** [comment]
You need to read the folder of SDK/QSPI_Flasher README, place the download algorithm in your Keil path.Then download and flash example "02-EXTMEM_BOOT, change routine(eg:03-LCD_Test) target to W25Qxx, download and flash it.
