### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by zapta** [WeActStudio/MiniSTM32H7xx#34]
Hello, FYI, the Aliexpress store link here is broken https://github.com/WeActStudio/MiniSTM32H7xx .  I didn't test other pages.

**Comment by zapta** [comment]
FYI, your link in platformio is also broken. 

https://community.platformio.org/t/strange-vendor-link-in-platformio-docs/33690/2

**Comment by WeActStudio** [comment]
It is normal

**Comment by zapta** [comment]
Yes, it's working now. In the past it gave an error page.

Thanks.
