### ISSUE TITLE
HQQVGA actually 120x80

### ISSUE THREAD

**Issue by Kabron287** [WeActStudio/MiniSTM32H7xx#9]
In the documentation HQQVGA framesize declared as 160x80 but in fact it is 120x80.
See attached pictire.
![HQQVGA](https://user-images.githubusercontent.com/2493191/101045540-6bcc1900-3591-11eb-93fe-0915bd79a76d.jpg)

**Comment by WeActTC** [comment]
It could be an error in the OpenMV documentation

**Comment by Kabron287** [comment]
I allready asked them about.
